repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        always_run: true
        pass_filenames: true
        files: ^.*\.py$
