[tool.black]
target-version = ["py38", "py39", "py310", "py311", "py312"]
preview = true

[tool.pyright]
exclude = ["**/__pycache__"]
include = ["bioimageio_collection_backoffice", "tests"]
pythonPlatform = "All"
pythonVersion = "3.8"
reportIncompatibleMethodOverride = true
reportMissingSuperCall = "error"
reportMissingTypeArgument = true
reportMissingTypeStubs = "warning"
reportUninitializedInstanceVariable = "error"
reportUnknownMemberType = false
reportUnnecessaryIsInstance = false
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"
reportUnusedVariable = "error"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
addopts = "--capture=no --failed-first"
testpaths = ["tests"]
