name: backup call

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

concurrency: backup-${{inputs.environment_name}}-call

env:
  S3_HOST: ${{vars.S3_HOST}}
  S3_BUCKET: ${{vars.S3_BUCKET}}
  S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
  S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
  RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment_name}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install .
      - run: backoffice backup
        env:
          S3_FOLDER: ${{inputs.S3_FOLDER}}
          ZENODO_API_ACCESS_TOKEN: ${{secrets.ZENODO_API_ACCESS_TOKEN}}

