name: backup
run-name: backup

on:
  workflow_run:
    workflows: [publish]
    types: [completed]
    branches: [main]
  workflow_dispatch:

concurrency: backup

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/backup_call.yaml@main
    with:
      environment_name: production

    secrets: inherit
