name: test backoffice and build docs

on: push

concurrency: test

# env:
#   S3_HOST: ${{vars.S3_HOST}}
#   S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
#   S3_FOLDER: ${{vars.S3_TEST_FOLDER}} # testing!
#   S3_TEST_BUCKET: ${{vars.S3_TEST_BUCKET}}
#   S3_TEST_FOLDER: ${{vars.S3_TEST_FOLDER}}
#   S3_PYTEST_FOLDER: ${{vars.S3_PYTEST_FOLDER}}
#   ZENODO_URL: ${{vars.ZENODO_TEST_URL}} # testing!
#   ZENODO_TEST_URL: ${{vars.ZENODO_TEST_URL}}
#   REVIEWERS: ${{vars.REVIEWERS}}
#   RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

#   S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
#   S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
#   ZENODO_API_ACCESS_TOKEN: ${{secrets.ZENODO_TEST_API_ACCESS_TOKEN}} # testing!
#   ZENODO_TEST_API_ACCESS_TOKEN: ${{secrets.ZENODO_TEST_API_ACCESS_TOKEN}}

#   TEST_PACKAGE_ID: ${{vars.TEST_PACKAGE_ID}}
#   TEST_PACKAGE_URL: ${{vars.TEST_PACKAGE_URL}}


jobs:
  initial-cleanup:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install .
      - run: backoffice wipe --bucket "${{vars.S3_TEST_BUCKET}}" --prefix "${{vars.S3_TEST_FOLDER}}"

  generate-initial-collection-json:
    needs: initial-cleanup
    uses: bioimage-io/collection/.github/workflows/generate_collection_json_call.yaml@main
    with:
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
    secrets: inherit

  test-stage:
    needs: generate-initial-collection-json
    uses: bioimage-io/collection/.github/workflows/stage_call.yaml@main
    with:
      resource_id: ${{vars.TEST_PACKAGE_ID}} # testing!
      package_url: ${{vars.TEST_PACKAGE_URL}} # testing!
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
    secrets: inherit

  test-publish:
    needs: test-stage
    uses: bioimage-io/collection/.github/workflows/publish_call.yaml@main
    with:
      resource_id: ${{vars.TEST_PACKAGE_ID}} # testing!
      stage_number: 1
      reviewer: 'github|${{github.actor_id}}'
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
      REVIEWERS: ${{vars.REVIEWERS}}
    secrets: inherit

  test-generate-collection-json:
    needs: test-publish
    uses: bioimage-io/collection/.github/workflows/generate_collection_json_call.yaml@main
    with:
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
    secrets: inherit


  test-generate-collection-staged-json:
    needs: test-publish
    uses: bioimage-io/collection/.github/workflows/generate_collection_json_call.yaml@main
    with:
      mode: 'staged'
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
    secrets: inherit

  test-backup:
    needs: test-generate-collection-json
    uses: bioimage-io/collection/.github/workflows/backup_call.yaml@main
    with:
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # testing!
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # testing!
      ZENODO_URL: ${{vars.ZENODO_TEST_URL}} # testing!
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install .[dev]
      - run: black . --check
      - run: pyright -p pyproject.toml
      - run: pytest
      - name: export documentation
        run: |
          pdoc \
          --mermaid \
          --logo https://bioimage.io/static/img/bioimage-io-logo.svg \
          --logo-link https://bioimage.io/ \
          --favicon https://bioimage.io/static/img/bioimage-io-icon-small.svg \
          --footer-text 'bioimageio_collection_backoffice' \
          -o ./docs bioimageio_collection_backoffice
      - run: cp README.md ./docs/
      - run: cp id_parts.json ./docs/
      - run: cp reviewers.json ./docs/
      - name: Deploy to gh-pages 🚀
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
