name: check compatibility ilastik

concurrency: ilastik

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/check_compatibility_ilastik.yaml
      - scripts/check_compatibility_ilastik.py
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *  # update compatibility once a day

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version_matrix: ${{ steps.cvm.outputs.version_matrix }}
    steps:
    - name: download version list
      run: wget https://files.ilastik.org/ilastik-versions-bmz.json
    - name: create version matrix
      id: cvm
      shell: python
      run: |
        import json
        import os

        with open("ilastik-versions-bmz.json") as f:
            vs = json.load(f)

        version_matrix = dict(include=[dict(v=v, env_url=f"https://files.ilastik.org/ilastik-{v}-Linux.yml") for v in vs])
        with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"version_matrix={version_matrix}", file=fh)

  run:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.version_matrix) }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Download ilastik env
      run: wget --output-document env.yaml ${{ matrix.env_url }}
    - name: ignore unrelated packages
      run: sed -i '/multi-hypotheses-tracking-with-gurobi/d; /gurobi-symlink/d' env.yaml
    - name: Setup ilastik env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: env.yaml
        cache-downloads: true
        cache-environment: true
    - name: install backoffice
      shell: bash -l {0}
      run: pip install .
    - name: test with ilastik ${{ matrix.v }}
      shell: bash -l {0}
      run: python scripts/check_compatibility_ilastik.py ${{ matrix.v }}
