name: generate collection.json
run-name: generate collection

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency: generate-collection-json


jobs:
  call:
    strategy:
      matrix:
        mode: [draft, published]
    uses: bioimage-io/collection/.github/workflows/generate_collection_json_call.yaml@main
    with:
      mode: ${{matrix.mode}}
      environment_name: production
    secrets: inherit
