name: generate collection.json
run-name: generate ${{inputs.mode}} collection for ${{vars.S3_BUCKET}}/${{vars.S3_FOLDER}}

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "determines which collection file to generate: 'published' (default) or 'staged'"
        required: false
        default: published
        type: string
  push:
    branches: [main]

concurrency: generate-collection-json-${{inputs.mode}}

env:
  S3_HOST: ${{vars.S3_HOST}}
  S3_BUCKET: ${{vars.S3_BUCKET}}
  S3_FOLDER: ${{vars.S3_FOLDER}}
  S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
  S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/generate_collection_json_call.yaml@main
    with:
      mode: ${{inputs.mode || 'published'}}
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_BUCKET}}
      S3_FOLDER: ${{vars.S3_FOLDER}}
    secrets: inherit
