name: generate collection.json call

on:
  workflow_call:
    inputs:
      mode:
        description: "determines which collection file to generate: 'published' (default) or 'draft'"
        required: false
        default: published
        type: string
      environment_name:
        required: true
        type: string

concurrency: generate-collection-json-call-${{inputs.environment_name}}-${{inputs.mode}}


jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment_name}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install .
      - run: backoffice generate_collection_json --mode=${{inputs.mode}}
        env:
          S3_HOST: ${{vars.S3_HOST}}
          S3_BUCKET: ${{vars.S3_BUCKET}}
          S3_FOLDER: ${{vars.S3_FOLDER}}
          S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
          S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
          BIOIMAGEIO_USER_ID: github|${{github.actor_id}}
