name: publish

on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: "Bioimageio ID of the resource - to be used to access the resource on S3"
        required: true
        type: string
      stage_number:
        description: stage number to publish
        required: true
        type: number

concurrency: ${{inputs.resource_id}}

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/publish_call.yaml@main
    with:
      resource_id: ${{inputs.resource_id}}
      stage_number: ${{inputs.stage_number}}
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_BUCKET}}
      S3_FOLDER: ${{vars.S3_FOLDER}}
    secrets: inherit
