name: request changes
run-name: request changes for ${{inputs.resource_id}}

on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: "Bioimageio ID of the resource - to be used to access the resource on S3"
        required: true
        type: string
      stage_number:  # TODO: remove
        description: DEPRECATED, will be removed soon
        required: false
        default: -1
        type: number
      reviewer:
        description: GitHub account name of bioimage.io maintainer requesting changes
        required: false
        default: 'auto detect'
        type: string
      reason:
        description: Why are changes required? What needs changing?
        required: true
        type: string
      sandbox:
        description: Use sandbox
        required: false
        default: false
        type: boolean

concurrency: ${{inputs.resource_id}}

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/request_changes_call.yaml@main
    with:
      concept_id: ${{inputs.resource_id}}
      reviewer: ${{inputs.reviewer == 'auto detect' && format('github|{0}', github.actor_id) || inputs.reviewer}}
      reason: ${{inputs.reason}}
      environment_name: ${{inputs.sandbox && 'sandbox' || 'production'}}
    secrets: inherit
