name: request changes

on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: "Bioimageio ID of the resource - to be used to access the resource on S3"
        required: true
        type: string
      stage_number:
        description: stage number
        required: true
        type: number
      reason:
        description: Why are changes required? What needs changing?
        required: true
        type: string

concurrency: ${{inputs.resource_id}}

env:
  S3_HOST: ${{vars.S3_HOST}}
  S3_BUCKET: ${{vars.S3_BUCKET}}
  S3_FOLDER: ${{vars.S3_FOLDER}}
  S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
  S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
  ZENODO_URL: ${{vars.ZENODO_URL}}
  ZENODO_API_ACCESS_TOKEN: ${{secrets.ZENODO_API_ACCESS_TOKEN}}

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/request_changes_call.yaml@main
    with:
      resource_id: '${{inputs.resource_id}}'
      stage_number: '${{inputs.stage_number}}'
      reason: '${{inputs.reason}}'
      S3_HOST: '${{vars.S3_HOST}}'
      S3_BUCKET: '${{vars.S3_BUCKET}}'
      S3_FOLDER: '${{vars.S3_FOLDER}}'
      ZENODO_URL: '${{vars.ZENODO_URL}}'
    secrets: inherit
