name: retest all bioimageio resources

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: use sandbox
        required: false
        default: true
        type: boolean

concurrency: retest-${{inputs.sandbox}}

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{inputs.sandbox && 'sandbox' || 'production'}}
    outputs:
      matrix: ${{steps.get_matrix.outputs.matrix}}

    steps:
      - run: wget ${{vars.S3_HOST}}/${{vars.S3_BUCKET}}/${{vars.S3_FOLDER}}/collection.json
      - run: wget ${{vars.S3_HOST}}/${{vars.S3_BUCKET}}/${{vars.S3_FOLDER}}/collection_draft.json
      - shell: python
        id: get_matrix
        run: |
          import json, os

          with open("collection.json") as f:
            collection = json.load(f)

          with open("collection_draft.json") as f:
            collection_draft = json.load(f)

          versions = [{"id": entry.get("nickname", entry["id"]), "v": "latest"} for entry in collection["collection"]]
          versions.extend([{"id": entry["id"], "v": "draft"} for entry in collection_draft["collection"])
          matrix = {"include": versions}
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            print(f"matrix={matrix}", file=f)

  test:
    needs: setup
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    uses: bioimage-io/collection/.github/workflows/test_call.yaml@main
    with:
      concept_id: ${{matrix.id}}
      version: ${{matrix.v}}
      conclude: ${{matrix.v == 'draft' && 'yes' || 'no'}}
      environment_name: ${{inputs.sandbox && 'sandbox' || 'production'}}
    secrets: inherit
