name: test bioimageio resource

on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: "Bioimage.io resource identifier"
        required: true
        type: string
      stage_number:
        description: stage number to test
        required: true
        type: number

concurrency: ${{inputs.resource_id}}

jobs:
  call:
    uses: bioimage-io/collection/.github/workflows/test_call.yaml@main
    with:
      resource_id: ${{inputs.resource_id}}
      version: staged/${{inputs.stage_number}}
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_BUCKET}}
      S3_FOLDER: ${{vars.S3_FOLDER}}
    secrets: inherit

# TODO: call emailer
