name: test stage call

on: push

concurrency: ${{inputs.resource_id}}

jobs:
  call:
    uses: ./.github/workflows/stage_call.yml
    with:
      resource_id: ${{vars.TEST_PACKAGE_ID}}
      package_url: ${{vars.TEST_PACKAGE_URL}}
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # using test bucket
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}} # using test folder
    secrets: inherit
