name: test stage call

on: push

concurrency: ${{inputs.resource_id}}

jobs:
  test-stage-wf:
    uses: ./.github/workflows/stage_call.yml
    with:
      resource_id: ${{vars.TEST_PACKAGE_ID}}
      package_url: ${{vars.TEST_PACKAGE_URL}}
      S3_HOST: ${{vars.S3_HOST}}
      S3_BUCKET: ${{vars.S3_TEST_BUCKET}} # using test bucket
      S3_FOLDER: ${{vars.S3_TEST_FOLDER}}/ci # using test folder
    secrets: inherit

  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install -r .github/scripts/requirements.txt
      - run: pip install black pyright pytest
      - run: black .
      - run: pyright -p pyproject.toml
      - run: pytest
